language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install flake8 mypy pytest-asyncio
script:
  - flake8 .
  - mypy --ignore-missing-imports ../kademlia
  - pytest
